### PR TITLE
Ignore build files and add ReadTheDocs link

### PR DESCRIPTION
**Pull request by TheReconPilot**
Since the documentation is built automatically (and since the build files are large), it is better to ignore them. Also added the `.vscode` folder to `.gitignore` in case someone uses it.

Added the documentation link to README.

### CODE REVIEW

**Comment by TheReconPilot** [comment]
Link: https://bharatsim.readthedocs.io/

We can do one of the following things:

1. I continue to keep this link updated from my Repo at TheReconPilot/bharatsim-tutorial
2. I delete this RTD page, and you publish the site from this main repo at JoyMonteiro/bharatsim-tutorial. At some point, we would have to do that anyway.

This is because now the unique name `bharatsim` is taken at ReadTheDocs. The name ownership is a thing to consider.

**Comment by JoyMonteiro** [comment]
Thanks for setting this up! yes, please delete the current RTD association. I'll set it up separately.

**Comment by TheReconPilot** [comment]
> Thanks for setting this up! yes, please delete the current RTD association. I'll set it up separately.

Deleted mine. It actually was really easy setting it up. Just logged into RTD through GitHub, create new project through Repo. Within 5 minutes it gets done, start to finish. 

The name `bharatsim` should be now available.

**Comment by JoyMonteiro** [comment]
Thanks! yes, it is now up and running.

**Pull request merged**
